pipeline {
    agent {
        docker {
            image 'python:3-alpine'
        }
    }
    stages {
        stage('Build') {
            steps {
                notifyBuild('STARTED')

                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    sh 'pip install django-crispy-forms'
                }
            }
        }
        stage('Test') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    sh 'pip install django-crispy-forms'
                    sh 'pip install django_jenkins'
                    sh 'pip install \'coverage==4.5.4\''
                    sh 'pip install pep8'
                    sh 'pip install pyflakes'
                    sh 'cd event_manager && python manage.py jenkins --enable-coverage'
                }
            }
            post {
                always {
                    junit 'event_manager/reports/junit.xml'

                    // Success or failure, always send notifications
                }
                success {
                    notifyBuild('SUCCESS')
                }
                failure {
                    notifyBuild('FAILED')
                }
            }
        }
    }
}

def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus = buildStatus ?: 'SUCCESS'

  // Default values
  def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def summary = "${subject} (${env.BUILD_URL})"
  def details = """<p>STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
    <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>"""

  // Send email
  emailext (
        subject: subject,
        body: details,
        recipientProviders: [
            [$class: 'CulpritsRecipientProvider'],
            [$class: 'DevelopersRecipientProvider'],
            [$class: 'RequesterRecipientProvider']
        ]
    )
}