pipeline {
    agent {
        docker {
            image 'python:3-alpine'
        }
    }
    stages {
        stage('Build') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    sh 'pip install django-crispy-forms'
                }
            }
        }
        stage('Test') {
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    sh 'pip install django-crispy-forms'
                    sh 'pip install django_jenkins'
                    sh 'pip install \'coverage==4.5.4\''
                    sh 'pip install pep8'
                    sh 'pip install pyflakes'
                    sh 'cd event_manager && python manage.py jenkins --enable-coverage'
                }
            }
            post {
                always {
                    junit 'cd event_manager && reports/junit.xml'
                }
            }
        }
    }
}