pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3-alpine'
                }
            }
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    // sh 'python event_manager/manage.py runserver'
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python:3-alpine'
                }
            }
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install django'
                    sh 'pip install pymysql'
                    sh 'pip install django-crispy-forms'
                    sh 'cd event_manager && python manage.py test'
                }
            }
            post {
                always {
                    junit 'output.xml'
                }
            }
        }
    }
}